=head1 NAME

B<saga_gui> - graphical user interface to the System for Automated Geoscientific Analyses
 
=head1 SYNOPSIS

B<saga_gui> [I<filename(.sprj,.sgrd,.shp)>]

=head1 DESCRIPTION

Graphical user interface to the System for Automated Geoscientific Analyses, a free and open source geographic information system used for editing and analysing spatial data. It includes a large number of modules for the analysis of vector, table, grid and image data.

=head1 BUGS

On the project website: I<http://www.saga-gis.org>, a list of known bugs can be found and new bug reports can be submitted.

=head1 AUTHORS

B<SAGA> was written by Olaf Conrad with help from a large number of contributers. This manual page was written by Johan Van de Wauw.
Both are released under the GNU General Public License v2.

More info  I<http://www.saga-gis.org>

=cut
